### PR TITLE
English documentation.

### PR DESCRIPTION
**Pull request by mzorec**
Work in progress

### CODE REVIEW

**Comment by liuliang-wt** [comment]
Thank you ~~~~~[flower]

**Comment by liuliang-wt** [comment]
dear， are you still working on this?

**Comment by mzorec** [comment]
Yes, sorry for the delays I will try to finish as soon as possible.

**Comment by liuliang-wt** [comment]
Thank you :)

**Comment by mzorec** [comment]
I've went through documentation and fixed gramatical errors. PR can be reviewed now.

**Comment by liuliang-wt** [comment]
thank you , if anything I can do for you ,let me know

**Pull request merged**
